"""add_email_verification_and_auth_tokens

Revision ID: 34a3d853481e
Revises: f7d668d4c5ae
Create Date: 2026-09-13 17:35:24.761349
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34a3d853481e'
down_revision: Union[str, Sequence[str], None] = 'f7d668d4c5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='app_auth_token_purpose', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_auth_token_expires_at', 'app_auth_token', ['expires_at'], unique=False)
    op.create_index('ix_app_auth_token_purpose_expires_at', 'app_auth_token', ['purpose', 'expires_at'], unique=False)
    op.create_index(op.f('ix_app_auth_token_token_hash'), 'app_auth_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_app_auth_token_user_id'), 'app_auth_token', ['user_id'], unique=False)
    op.create_index('ix_app_auth_token_user_purpose', 'app_auth_token', ['user_id', 'purpose'], unique=False)
    op.add_column('app_user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'email_verified_at')
    op.drop_index('ix_app_auth_token_user_purpose', table_name='app_auth_token')
    op.drop_index(op.f('ix_app_auth_token_user_id'), table_name='app_auth_token')
    op.drop_index(op.f('ix_app_auth_token_token_hash'), table_name='app_auth_token')
    op.drop_index('ix_app_auth_token_purpose_expires_at', table_name='app_auth_token')
    op.drop_index('ix_app_auth_token_expires_at', table_name='app_auth_token')
    op.drop_table('app_auth_token')
    # ### end Alembic commands ###
