"""add_subscription_app_user_link

Revision ID: 3e90d898256e
Revises: fb9b002f2f59
Create Date: 2026-08-25 07:04:36.060784
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e90d898256e'
down_revision: Union[str, Sequence[str], None] = 'fb9b002f2f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('razorpay_subscription', sa.Column('app_user_id', sa.Integer(), nullable=True))
    op.create_index('ix_razorpay_subscription_app_user_id', 'razorpay_subscription', ['app_user_id'], unique=False)
    op.create_foreign_key(None, 'razorpay_subscription', 'app_user', ['app_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'razorpay_subscription', type_='foreignkey')
    op.drop_index('ix_razorpay_subscription_app_user_id', table_name='razorpay_subscription')
    op.drop_column('razorpay_subscription', 'app_user_id')
    # ### end Alembic commands ###
