"""add_auth_rate_limit

Revision ID: 949f7bfa97ec
Revises: 3e90d898256e
Create Date: 2026-08-25 07:49:32.618879
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '949f7bfa97ec'
down_revision: Union[str, Sequence[str], None] = '3e90d898256e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_auth_rate_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('throttle_key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('SIGN_IN', 'SIGN_UP', name='app_auth_rate_limit_action', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_auth_rate_limit_blocked_until', 'app_auth_rate_limit', ['blocked_until'], unique=False)
    op.create_index(op.f('ix_app_auth_rate_limit_throttle_key'), 'app_auth_rate_limit', ['throttle_key'], unique=False)
    op.create_index('ix_app_auth_rate_limit_window_started_at', 'app_auth_rate_limit', ['window_started_at'], unique=False)
    op.create_index('uq_app_auth_rate_limit_key_action', 'app_auth_rate_limit', ['throttle_key', 'action'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_app_auth_rate_limit_key_action', table_name='app_auth_rate_limit')
    op.drop_index('ix_app_auth_rate_limit_window_started_at', table_name='app_auth_rate_limit')
    op.drop_index(op.f('ix_app_auth_rate_limit_throttle_key'), table_name='app_auth_rate_limit')
    op.drop_index('ix_app_auth_rate_limit_blocked_until', table_name='app_auth_rate_limit')
    op.drop_table('app_auth_rate_limit')
    # ### end Alembic commands ###
