"""add_admin_flag_and_feedback_status

Revision ID: f7d668d4c5ae
Revises: 949f7bfa97ec
Create Date: 2026-09-12 14:55:40.088721
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7d668d4c5ae'
down_revision: Union[str, Sequence[str], None] = '949f7bfa97ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_feedback', sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'RESOLVED', name='app_feedback_status', native_enum=False, length=16), server_default='NEW', nullable=False))
    op.create_index('ix_app_feedback_status', 'app_feedback', ['status'], unique=False)
    op.create_index('ix_app_feedback_status_submitted', 'app_feedback', ['status', 'submitted_at'], unique=False)
    op.add_column('app_user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_app_user_is_admin', 'app_user', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_user_is_admin', table_name='app_user')
    op.drop_column('app_user', 'is_admin')
    op.drop_index('ix_app_feedback_status_submitted', table_name='app_feedback')
    op.drop_index('ix_app_feedback_status', table_name='app_feedback')
    op.drop_column('app_feedback', 'status')
    # ### end Alembic commands ###
