"""add_user_accounts_and_feedback

Revision ID: fb9b002f2f59
Revises: 15d6654b1413
Create Date: 2026-08-24 15:05:11.337468
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb9b002f2f59'
down_revision: Union[str, Sequence[str], None] = '15d6654b1413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_algorithm', sa.String(length=32), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_email_normalized'), 'app_user', ['email_normalized'], unique=True)
    op.create_index('ix_app_user_is_active', 'app_user', ['is_active'], unique=False)
    op.create_table('app_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_feedback_user_id'), 'app_feedback', ['user_id'], unique=False)
    op.create_index('ix_app_feedback_user_submitted', 'app_feedback', ['user_id', 'submitted_at'], unique=False)
    op.create_table('app_user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_user_session_expires_at', 'app_user_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_user_session_session_token_hash'), 'app_user_session', ['session_token_hash'], unique=True)
    op.create_index('ix_app_user_session_user_id', 'app_user_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_user_session_user_id', table_name='app_user_session')
    op.drop_index(op.f('ix_app_user_session_session_token_hash'), table_name='app_user_session')
    op.drop_index('ix_app_user_session_expires_at', table_name='app_user_session')
    op.drop_table('app_user_session')
    op.drop_index('ix_app_feedback_user_submitted', table_name='app_feedback')
    op.drop_index(op.f('ix_app_feedback_user_id'), table_name='app_feedback')
    op.drop_table('app_feedback')
    op.drop_index('ix_app_user_is_active', table_name='app_user')
    op.drop_index(op.f('ix_app_user_email_normalized'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
