import reflex as rx


def app_icon(name: rx.Var | str, class_name: str = "h-4 w-4") -> rx.Component:
    """Render one of the finite icon names this app uses.

    Every branch calls rx.icon with a literal name so the production build can
    tree-shake the icon library instead of bundling the whole catalog.
    """
    return rx.match(
        name,
        ("activity", rx.icon("activity", class_name=class_name)),
        ("align-left", rx.icon("align-left", class_name=class_name)),
        ("archive", rx.icon("archive", class_name=class_name)),
        ("arrow-down", rx.icon("arrow-down", class_name=class_name)),
        ("arrow-up", rx.icon("arrow-up", class_name=class_name)),
        (
            "arrow-down-right",
            rx.icon("arrow-down-right", class_name=class_name),
        ),
        ("arrow-up-right", rx.icon("arrow-up-right", class_name=class_name)),
        ("award", rx.icon("award", class_name=class_name)),
        ("badge-check", rx.icon("badge-check", class_name=class_name)),
        (
            "badge-dollar-sign",
            rx.icon("badge-dollar-sign", class_name=class_name),
        ),
        ("banknote", rx.icon("banknote", class_name=class_name)),
        ("bell-ring", rx.icon("bell-ring", class_name=class_name)),
        ("briefcase", rx.icon("briefcase", class_name=class_name)),
        ("calculator", rx.icon("calculator", class_name=class_name)),
        ("calendar", rx.icon("calendar", class_name=class_name)),
        ("calendar-check", rx.icon("calendar-check", class_name=class_name)),
        ("calendar-clock", rx.icon("calendar-clock", class_name=class_name)),
        ("calendar-plus", rx.icon("calendar-plus", class_name=class_name)),
        ("calendar-range", rx.icon("calendar-range", class_name=class_name)),
        ("calendar-x", rx.icon("calendar-x", class_name=class_name)),
        ("chart-line", rx.icon("chart-line", class_name=class_name)),
        ("chart-pie", rx.icon("chart-pie", class_name=class_name)),
        (
            "chart-no-axes-column",
            rx.icon("chart-no-axes-column", class_name=class_name),
        ),
        ("chevron-down", rx.icon("chevron-down", class_name=class_name)),
        ("chevron-up", rx.icon("chevron-up", class_name=class_name)),
        (
            "chevrons-up-down",
            rx.icon("chevrons-up-down", class_name=class_name),
        ),
        ("circle-alert", rx.icon("circle-alert", class_name=class_name)),
        ("circle-check", rx.icon("circle-check", class_name=class_name)),
        ("circle-dashed", rx.icon("circle-dashed", class_name=class_name)),
        ("circle-dot", rx.icon("circle-dot", class_name=class_name)),
        ("circle-help", rx.icon("circle-help", class_name=class_name)),
        ("circle-slash", rx.icon("circle-slash", class_name=class_name)),
        ("cloud-upload", rx.icon("cloud-upload", class_name=class_name)),
        ("columns-3", rx.icon("columns-3", class_name=class_name)),
        ("cookie", rx.icon("cookie", class_name=class_name)),
        ("copy", rx.icon("copy", class_name=class_name)),
        ("credit-card", rx.icon("credit-card", class_name=class_name)),
        ("crown", rx.icon("crown", class_name=class_name)),
        ("database", rx.icon("database", class_name=class_name)),
        ("database-zap", rx.icon("database-zap", class_name=class_name)),
        ("dollar-sign", rx.icon("dollar-sign", class_name=class_name)),
        ("eraser", rx.icon("eraser", class_name=class_name)),
        ("eye", rx.icon("eye", class_name=class_name)),
        ("eye-off", rx.icon("eye-off", class_name=class_name)),
        ("file-lock", rx.icon("file-lock", class_name=class_name)),
        ("file-text", rx.icon("file-text", class_name=class_name)),
        (
            "file-spreadsheet",
            rx.icon("file-spreadsheet", class_name=class_name),
        ),
        ("fingerprint", rx.icon("fingerprint", class_name=class_name)),
        ("gauge", rx.icon("gauge", class_name=class_name)),
        ("gem", rx.icon("gem", class_name=class_name)),
        ("globe-lock", rx.icon("globe-lock", class_name=class_name)),
        ("graduation-cap", rx.icon("graduation-cap", class_name=class_name)),
        ("grid-2x2", rx.icon("grid-2x2", class_name=class_name)),
        ("handshake", rx.icon("handshake", class_name=class_name)),
        ("hash", rx.icon("hash", class_name=class_name)),
        ("heart", rx.icon("heart", class_name=class_name)),
        ("heart-pulse", rx.icon("heart-pulse", class_name=class_name)),
        ("hourglass", rx.icon("hourglass", class_name=class_name)),
        ("info", rx.icon("info", class_name=class_name)),
        ("key-round", rx.icon("key-round", class_name=class_name)),
        (
            "layout-dashboard",
            rx.icon("layout-dashboard", class_name=class_name),
        ),
        ("life-buoy", rx.icon("life-buoy", class_name=class_name)),
        ("lightbulb", rx.icon("lightbulb", class_name=class_name)),
        ("list-checks", rx.icon("list-checks", class_name=class_name)),
        ("lock", rx.icon("lock", class_name=class_name)),
        ("mail", rx.icon("mail", class_name=class_name)),
        ("map-pin", rx.icon("map-pin", class_name=class_name)),
        ("moon", rx.icon("moon", class_name=class_name)),
        ("package", rx.icon("package", class_name=class_name)),
        ("percent", rx.icon("percent", class_name=class_name)),
        ("receipt", rx.icon("receipt", class_name=class_name)),
        ("receipt-text", rx.icon("receipt-text", class_name=class_name)),
        ("repeat", rx.icon("repeat", class_name=class_name)),
        ("rocket", rx.icon("rocket", class_name=class_name)),
        ("rotate-ccw", rx.icon("rotate-ccw", class_name=class_name)),
        ("rows-3", rx.icon("rows-3", class_name=class_name)),
        ("scan-search", rx.icon("scan-search", class_name=class_name)),
        ("scatter-chart", rx.icon("scatter-chart", class_name=class_name)),
        ("scissors", rx.icon("scissors", class_name=class_name)),
        ("search", rx.icon("search", class_name=class_name)),
        ("search-check", rx.icon("search-check", class_name=class_name)),
        ("search-x", rx.icon("search-x", class_name=class_name)),
        ("shapes", rx.icon("shapes", class_name=class_name)),
        ("sheet", rx.icon("sheet", class_name=class_name)),
        ("shield", rx.icon("shield", class_name=class_name)),
        ("shield-check", rx.icon("shield-check", class_name=class_name)),
        ("shopping-cart", rx.icon("shopping-cart", class_name=class_name)),
        ("shuffle", rx.icon("shuffle", class_name=class_name)),
        ("sparkles", rx.icon("sparkles", class_name=class_name)),
        ("sprout", rx.icon("sprout", class_name=class_name)),
        (
            "table-properties",
            rx.icon("table-properties", class_name=class_name),
        ),
        ("table", rx.icon("table", class_name=class_name)),
        ("tag", rx.icon("tag", class_name=class_name)),
        ("tags", rx.icon("tags", class_name=class_name)),
        ("toggle-left", rx.icon("toggle-left", class_name=class_name)),
        ("trending-down", rx.icon("trending-down", class_name=class_name)),
        ("trending-up", rx.icon("trending-up", class_name=class_name)),
        ("triangle-alert", rx.icon("triangle-alert", class_name=class_name)),
        ("type", rx.icon("type", class_name=class_name)),
        ("user-check", rx.icon("user-check", class_name=class_name)),
        ("user-cog", rx.icon("user-cog", class_name=class_name)),
        ("user-plus", rx.icon("user-plus", class_name=class_name)),
        ("user-round", rx.icon("user-round", class_name=class_name)),
        ("user-x", rx.icon("user-x", class_name=class_name)),
        ("users", rx.icon("users", class_name=class_name)),
        ("users-round", rx.icon("users-round", class_name=class_name)),
        ("wand-sparkles", rx.icon("wand-sparkles", class_name=class_name)),
        ("wrench", rx.icon("wrench", class_name=class_name)),
        rx.icon("circle-dot", class_name=class_name),
    )
